### ISSUE TITLE
Polling Consumer liest von DB, transformiert und speichert in Dropbox/Email

### ISSUE THREAD

**Issue by carola89** [carola89/WMPM16#3]

**Comment by carola89** [comment]
Einmal pro Tag werden die Daten, welche vom Smart Meter (wir gehen davon aus, dass das Smart Meter die Daten in einer Datenbank ablegt, an dieser Stelle sei auch erwähnt, dass wir nicht von einem “klassischem” Smart Meter ausgehen, dies nur den Stromverbrauch misst) produziert werden, aus der Datenbank ausgelesen und die Verbrauchswerte via Email/Dropbox an die einzelnen Firmen (Gas-, Strom-, Warmwasserbetreibern, usw.) geschickt.

**Comment by patrick089** [comment]
Done
